apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-deployed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded: ArgoCD
  name: test-review-fe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-review-fe
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: test-review/microservices/frontend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
