apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 

  
configMapGenerator:
- envs:
  - config.env
  name: env-configs
  namespace: test-be

secretGenerator:
  - name: mongodb-secrets
    envs:
      - mongodb-secrets.env
    namespace: test-be

generatorOptions:
 disableNameSuffixHash: true